### ISSUE TITLE
Overlapping code blocks

### ISSUE THREAD

**Issue by acabhishek942** [chevah/styleguide#22]
Code blocks in Python and HTML section are overlapping with the menu of the styleguide. Please see the attached image.
![some](https://cloud.githubusercontent.com/assets/7778186/16045445/085e9eac-3266-11e6-92a8-d1e3005405c0.png)

**Comment by adiroiban** [comment]
Thanks for the report. I have no idea how to fix it... and for now I consider it a minor issue.... is better to just rewrite the whole CSS for this site... or re-write the whole site.

we can leave this issue opened and see if we fix it using the current css ... or while refactoring the site

thanks again

**Comment by atykhonov** [comment]
I was just curious how this documentation could looks like using [sphinx](http://www.sphinx-doc.org/en/stable/) + [sphinx_rtd_theme](http://www.writethedocs.org/guide/tools/sphinx-themes/). Take a look please: [Chevah Style Guide](http://atykhonov.github.io/).

**Comment by adiroiban** [comment]
@atykhonov thanks ... yep, we can also move it to read the docs :) 

the long term plan is to refactor this documentation into something like commons.chevah.com and use it to document how we roll :)

beside styleguide, the current documentation include information about how we manage the release.... how we manage the tickets and tech debt ... and I hope that we will extend it to also include how we manage our infrastructure, our hiring and other business and operation things.... 

the goal is to lay the foundation for an open business https://en.wikipedia.org/wiki/Open_business

**Comment by adiroiban** [comment]
then we also http://binary.chevah.com/production/python/ ... which is a free alternative to ActiveState and for which it would be nice to create a website and to start to promote it ... as we have pretty recent python 2.7 python distribution for all kind of exotic operating systems.

**Comment by atykhonov** [comment]
> the long term plan is to refactor this documentation into something like commons.chevah.com and use it to document how we roll :)

Well, if you would like, I could push all files that are currently used for generation of 'http://atykhonov.github.com' to my github repository, or to the newly created branch at `chevah/styleguide`. So that, you will be able to generate the site (by means of `make html`), copy it to the `commons.chevah.com`, and it would be ready.

> beside styleguide, the current documentation include information about how we manage the release.... how we manage the tickets and tech debt ... and I hope that we will extend it to also include how we manage our infrastructure, our hiring and other business and operation things.... 

Yes, that's right, it does include much more than just style guides. I've just borrowed the title from the existing web-site...

By the way, I was curious how easy it would be to migrate the documentation to something else than `pelican`. And with `sphinx` it was quite easy. I just generated `conf.py` by means of `sphinx-quickstart`, copied rst-files, removed some pelican-specific lines from rst-files, executed `make html`, and deployed html-files to my github account. That's all. (I'm ot sure how easy it would be to go with read the docs).

**Comment by atykhonov** [comment]
> then we also http://binary.chevah.com/production/python/ ..

Does it contain all archives that are mentioned in the documentation ([installation](https://www.sftpplus.com/documentation/sftpplus/latest/installation/unix.html))? I would like to try it to install.

**Comment by adiroiban** [comment]
@atykhonov nope... there is just the python base distribution.... 

the final commercial products is python-distribution + 20 (or more) python open source packages   + our close source code

**Comment by atykhonov** [comment]
@adiroiban ah, indeed. If there is a chance to get close source code (sftpplus-os-arch-version.tar.gz), let me know please. It would great to try it.

**Comment by adiroiban** [comment]
ok. so the easiest  way to do is to put it to read the docs, with the read the docs theme.

the current site is not that bad

still, the Chevah project is dedicated for creating a final application, hopefully with a commercial success and I think that a bit of branding is important for any commercial success :)

hence, it would be nice to exercise the branding and investigate the easiest way in which we can create a site with branding :)

**Comment by atykhonov** [comment]
> then we also http://binary.chevah.com/production/python/ ... which is a free alternative to ActiveState and for which it would be nice to create a website and to start to promote it

How this site might looks like? Could you please provide good example of similar site?

**Comment by atykhonov** [comment]
> hence, it would be nice to exercise the branding and investigate the easiest way in which we can create a site with branding :)

Thanks! In this case, I'll try to do it.

**Comment by adiroiban** [comment]
This was fixed by @lesingerouge
