### ISSUE TITLE
Review and provide feedback for chevah styleguide 

### ISSUE THREAD

**Issue by dispera** [chevah/styleguide#37]
I have reviewed Overview/Generic/Review/Tickets sections

For this first time, I did what I believed was the best format for you as a reviewer to easily spot the differences. I created a word document in which you can see each line for which I humbly propose a change (mostly quick gramatical errors and sometimes what I think would look best, or send the message better). 
The format I used is 'git like' format, where I show the original and modified lines, the parts to be changed/removed in red, and the parts modified in green:
[Chevah Styleguide  - Review 1 - Diego.docx](https://github.com/chevah/styleguide/files/612285/Chevah.Styleguide.-.Review.1.-.Diego.docx)

Please let me know if it is best next time to just paste all the information here or do something like this with Markdown format for columns (it would lack the colors and seems nicely arranged, but in reality I think it's harder to compare EVERY change like this):

Original | Modified
--------|----------
Reviewer is the person responsible for checking the code or changes. | The reviewer is the person responsible for checking the code or changes.

**Comment by dispera** [comment]
@adiroiban Hi Adi - I am not sure I should put you as an assignee for my issues too, so you get notifications, or just mentioning your name like this is alright. So you can check my review and if you agree with my modifications I can go on and submit a PR :)
I will continue with the styleguide review now.

**Comment by adiroiban** [comment]
docs is not our style... and I find it hard to use

please create a branch and submit a PR with your changes. in this way we can get an automatic diff.

see https://github.com/chevah/styleguide/pull/36

**Comment by dispera** [comment]
Alright, I'm on it 👍

**Comment by dispera** [comment]
I closed issue #37 which I wrongly created into /styleguide, following up on #23 on /onboarding
