### ISSUE TITLE
Add documentation section in the styleguide

### ISSUE THREAD

**Issue by hcs0** [chevah/styleguide#44]
There are some styleguide points available at https://github.com/chevah/server

But there are additional details that is not readily available

- How to break long lines of logs
- How to link internally vs externally
- Which header format to use like:

heading 1 -> #
heading 2 -> =
heading 3 -> -
heading 4 -> ^

May be in its own page on a dedicated section about documentation best practice, rst markup tips etc.

**Comment by adiroiban** [comment]
we can start a page dedicated to best practices in writing the documentation.

and there we can talk about how to create a documentation page... how to write the introductory paragraph, where to put the local table of content... how to organize the headings/sections

**Comment by hcs0** [comment]
Ticket ID for this is at  #3858

**Comment by hcs0** [comment]
Closing due to #46
